#! bin/bash

#get start sectid  and   end sectid
full_file_name=`basename $0`
#echo  $full_file_name
file_name=$(echo "$full_file_name" | cut -f 1 -d '.')
#echo  $file_name
start_sector_id=`echo $file_name | cut -d \- -f 3`
end_sector_id=`echo $file_name | cut -d \- -f 4`
#echo  $start_sector_id
#echo  $end_sector_id
dest_ip="10.100.19.178"
dest_port="8178"
sector_prefix_name="s-t0397837-"


check_log=$file_name.log
#clean exist log file
rm -rf  $check_log

#list all sector numbers in a txt  
cd  /data

for  cur_sector_id  in `seq $end_sector_id`
do
    if  [ $cur_sector_id -ge $start_sector_id ];then
        #echo  "当前遍历的扇区ID为:"  $cur_sector_id
        echo "正在拷贝的sealed文件为: http://$dest_ip:$dest_port/sealed/$sector_prefix_name$cur_sector_id"
        wget  -c -r -np -nH  http://$dest_ip:$dest_port/sealed/$sector_prefix_name$cur_sector_id   /data/sealed/$sector_prefix_name$cur_sector_id  
        echo "正在拷贝的cache文件为:  http://$dest_ip:$dest_port/cache/$sector_prefix_name$cur_sector_id/" 
        wget  -c -r -np -nH  http://$dest_ip:$dest_port/cache/$sector_prefix_name$cur_sector_id/   /data/cache/$sector_prefix_name$cur_sector_id/ 

    fi
done
